# Generated by Django 4.1.1 on 2022-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rank',
            field=models.FloatField(default=0),
        ),
    ]
