# Generated by Django 4.1.1 on 2022-09-08 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0002_alter_director_managers_remove_director_movies_and_more'),
        ('movies', '0002_alter_movie_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directors.director')),
            ],
            managers=[
                ('csv_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            managers=[
                ('csv_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='movie',
            managers=[
                ('csv_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AlterField(
            model_name='movie',
            name='rank',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='moviedirector',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
