# Generated by Django 4.1.1 on 2022-09-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviedirector_moviegenre_alter_movie_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviegenre',
            old_name='name',
            new_name='genre',
        ),
    ]
