# Generated by Django 4.1.1 on 2022-09-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_moviedirector_movie_alter_moviegenre_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_genres', to='movies.movie'),
        ),
    ]
