# Generated by Django 4.1.1 on 2022-09-08 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_moviegenre_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedirector',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_directors', to='movies.movie'),
        ),
    ]
