# Generated by Django 4.1.1 on 2022-09-08 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='director',
            managers=[
                ('csv_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='director',
            name='movies',
        ),
        migrations.CreateModel(
            name='DirectorGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('prob', models.FloatField()),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directors.director')),
            ],
            managers=[
                ('csv_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
