# Generated by Django 4.1.1 on 2022-09-08 07:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actor',
            managers=[
                ('csv_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('csv_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
