# Generated by Django 4.1.1 on 2022-09-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_moviedirector_movie_alter_moviegenre_movie'),
        ('actors', '0002_alter_actor_managers_alter_role_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_roles', to='actors.actor'),
        ),
        migrations.AlterField(
            model_name='role',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_movies', to='movies.movie'),
        ),
    ]
