# Generated by Django 4.1.1 on 2022-09-08 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_moviedirector_movie'),
        ('actors', '0005_alter_role_actor_alter_role_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
